"""Immutable ru-mvp-1 rule tuple part."""

from telegram_lead_discovery.detection.catalog_types import SeedRule, _r


RULES_V1_A: tuple[SeedRule, ...] = (
    _r(
        "NEG-SPAM-001",
        100,
        "spam",
        "hard_exclusion",
        0,
        r"\b(?:казино|слоты|ставки на спорт|букмекер|джекпот)\b",
        "spam_gambling",
    ),
    _r(
        "NEG-SPAM-002",
        101,
        "spam",
        "hard_exclusion",
        0,
        r"\b(?:гарантированный заработок|быстрый заработок|доход без вложений|крипто[- ]?сигналы|раздача криптовалюты)\b",
        "spam_income",
    ),
    _r(
        "NEG-SPAM-003",
        102,
        "spam",
        "hard_exclusion",
        0,
        r"\b(?:рассылка по чатам|массовая рассылка|накрутка подписчиков|накрутка реакций)\b",
        "spam_bulk",
    ),
    _r(
        "NEG-ADV-001",
        120,
        "advertising",
        "hard_exclusion",
        0,
        r"\b(?:мы|наша команда|наше агентство)\b.{0,80}\b(?:делаем|разрабатываем|создаём|оказываем|предлагаем)\b",
        "advertising_provider",
    ),
    _r(
        "NEG-ADV-002",
        121,
        "advertising",
        "hard_exclusion",
        0,
        r"\b(?:скидка|акция|спецпредложение|специальное предложение)\b.{0,80}\b(?:на сайт|на разработку|на бота|на услуги|до пятницы|до конца месяца)\b",
        "advertising_promo",
    ),
    _r(
        "NEG-ADV-003",
        122,
        "advertising",
        "hard_exclusion",
        0,
        r"\b(?:принимаем заказы|свободны для новых проектов|возьмём ваш проект|закажите у нас)\b",
        "advertising_solicitation",
    ),
    _r(
        "NEG-VAC-001",
        140,
        "vacancy",
        "hard_exclusion",
        0,
        r"\b(?:вакансия|открыта позиция|открыта вакансия|ищем сотрудника)\b",
        "vacancy_marker",
    ),
    _r(
        "NEG-VAC-002",
        141,
        "vacancy",
        "hard_exclusion",
        0,
        r"\b(?:в штат|полная занятость|частичная занятость|оформление по тк|трудоустройство)\b",
        "vacancy_employment",
    ),
    _r(
        "NEG-VAC-003",
        142,
        "vacancy",
        "hard_exclusion",
        0,
        r"\b(?:зарплата|оклад)\b\s*(?:от\s*)?\d[\d\s]{2,}",
        "vacancy_salary",
    ),
    _r(
        "NEG-VAC-004",
        143,
        "vacancy",
        "hard_exclusion",
        0,
        r"(?:https?://)?(?:www\.)?(?:hh\.ru|career\.habr\.com)/\S+",
        "vacancy_link",
    ),
    _r(
        "NEG-VAC-005",
        144,
        "vacancy",
        "hard_exclusion",
        0,
        r"\b(?:присылайте резюме|отправляйте резюме|откликнуться на вакансию|испытательный срок)\b",
        "vacancy_application",
    ),
    _r(
        "SVC-WEB-001",
        200,
        "websites",
        "service_fit",
        12,
        r"\b(?:сайт(?:а|е|ом|у|ы|ов)?|лендинг(?:а|е|и|ов)?|веб[- ]?приложени(?:е|я|ю|ем|й)|frontend|backend|фронтенд|бэкенд)\b",
        "service_websites",
    ),
    _r(
        "SVC-WEB-002",
        201,
        "websites",
        "service_fit",
        8,
        r"\b(?:wordpress|tilda|webflow|react|vue|django|fastapi)\b",
        "service_web_stack",
    ),
    _r(
        "SVC-BOT-001",
        210,
        "telegram_bots",
        "service_fit",
        12,
        r"\b(?:telegram|телеграм|тг)\b.{0,30}\b(?:бот(?:а|е|ом|у|ы|ов)?|mini app|мини[- ]?приложени(?:е|я))\b",
        "service_telegram_bot",
    ),
    _r(
        "SVC-BOT-002",
        211,
        "telegram_bots",
        "service_fit",
        8,
        r"\b(?:чат[- ]?бот(?:а|ы|ов)?|бот для (?:заказов|оплаты|поддержки|записи))\b",
        "service_chatbot",
    ),
)
