from __future__ import annotations

# Minimal DET-A subset sufficient for golden fixtures + full catalog loader later.
RULES: list[dict] = [
    {
        "stable_rule_id": "NEG-SPAM-001",
        "kind": "hard_exclusion",
        "target": "spam",
        "dimension": "hard_exclusion",
        "weight": 0,
        "priority": 100,
        "pattern": r"\b(?:казино|слоты|ставки на спорт|букмекер|джекпот)\b",
        "explanation_code": "spam_gambling",
    },
    {
        "stable_rule_id": "NEG-ADV-001",
        "kind": "hard_exclusion",
        "target": "advertising",
        "dimension": "hard_exclusion",
        "weight": 0,
        "priority": 120,
        "pattern": r"\b(?:мы|наша команда|наше агентство)\b.{0,80}\b(?:делаем|разрабатываем|создаём|оказываем|предлагаем)\b",
        "explanation_code": "advertising_provider",
    },
    {
        "stable_rule_id": "NEG-VAC-001",
        "kind": "hard_exclusion",
        "target": "vacancy",
        "dimension": "hard_exclusion",
        "weight": 0,
        "priority": 140,
        "pattern": r"\b(?:вакансия|открыта позиция|открыта вакансия|ищем сотрудника)\b",
        "explanation_code": "vacancy_marker",
    },
    {
        "stable_rule_id": "SVC-WEB-001",
        "kind": "service",
        "target": "websites",
        "dimension": "service_fit",
        "weight": 12,
        "priority": 200,
        "pattern": r"\b(?:сайт(?:а|е|ом|у|ы|ов)?|лендинг(?:а|е|и|ов)?|веб[- ]?приложени(?:е|я|ю|ем|й)|frontend|backend|фронтенд|бэкенд)\b",
        "explanation_code": "service_websites",
    },
    {
        "stable_rule_id": "SVC-BOT-001",
        "kind": "service",
        "target": "telegram_bots",
        "dimension": "service_fit",
        "weight": 12,
        "priority": 210,
        "pattern": r"\b(?:telegram|телеграм|тг)\b.{0,30}\b(?:бот(?:а|е|ом|у|ы|ов)?|mini app|мини[- ]?приложени(?:е|я))\b",
        "explanation_code": "service_telegram_bot",
    },
    {
        "stable_rule_id": "SVC-INT-001",
        "kind": "service",
        "target": "integrations_api",
        "dimension": "service_fit",
        "weight": 12,
        "priority": 220,
        "pattern": r"\b(?:интеграц(?:ия|ии|ию|ией)|api|апи|webhook|вебхук)\b",
        "explanation_code": "service_integration",
    },
    {
        "stable_rule_id": "SVC-AUT-001",
        "kind": "service",
        "target": "automation_parsers",
        "dimension": "service_fit",
        "weight": 12,
        "priority": 230,
        "pattern": r"\b(?:автоматизац(?:ия|ии|ию|ией)|автоматизировать|автоматизируем|автоматизируется|парсер(?:а|ы|ов)?|парсинг|скрейпинг|scraping)\b",
        "explanation_code": "service_automation",
    },
    {
        "stable_rule_id": "SVC-ECOM-001",
        "kind": "service",
        "target": "ecommerce",
        "dimension": "service_fit",
        "weight": 12,
        "priority": 240,
        "pattern": r"\b(?:интернет[- ]?магазин(?:а|е|ы|ов)?|e[- ]?commerce|электронн(?:ая|ой) коммерци(?:я|и))\b",
        "explanation_code": "service_ecommerce",
    },
    {
        "stable_rule_id": "POS-DIR-001",
        "kind": "positive_intent",
        "target": "direct_order",
        "dimension": "intent",
        "weight": 15,
        "priority": 300,
        "pattern": r"\b(?:нужно|надо|хочу|хотим|планирую|планируем)\b.{0,100}\b(?:сделать|разработать|создать|доработать|исправить|настроить|подключить|интегрировать|автоматизировать|перенести|запустить)\b",
        "explanation_code": "intent_direct_need",
    },
    {
        "stable_rule_id": "POS-CTR-001",
        "kind": "positive_intent",
        "target": "contractor_search",
        "dimension": "intent",
        "weight": 14,
        "priority": 320,
        "pattern": r"\b(?:ищу|ищем|нужен|нужна|нужны|требуется|требуются)\b.{0,80}\b(?:разработчик(?:а|и|ов)?|программист(?:а|ы|ов)?|фрилансер(?:а|ы|ов)?|специалист(?:а|ы|ов)?|подрядчик(?:а|и|ов)?|исполнитель|команда|агентство)\b",
        "explanation_code": "intent_contractor_search",
    },
    {
        "stable_rule_id": "POS-REC-001",
        "kind": "positive_intent",
        "target": "recommendation_request",
        "dimension": "intent",
        "weight": 10,
        "priority": 340,
        "pattern": r"\b(?:посоветуйте|порекомендуйте|можете посоветовать|можете порекомендовать)\b.{0,100}\b(?:разработчик(?:а)?|программист(?:а)?|специалист(?:а)?|подрядчик(?:а)?|исполнитель|команду|агентство)\b",
        "explanation_code": "intent_recommend_person",
    },
    {
        "stable_rule_id": "POS-POT-001",
        "kind": "positive_intent",
        "target": "potential_need",
        "dimension": "intent",
        "weight": 6,
        "priority": 360,
        "pattern": r"\b(?:можно ли|реально ли|как лучше|как можно|как)\b.{0,100}\b(?:сделать|реализовать|подключить|интегрировать|автоматизировать|перенести|собрать)\b",
        "explanation_code": "intent_potential_how",
    },
    {
        "stable_rule_id": "SIG-BUD-001",
        "kind": "signal",
        "target": "budget_present",
        "dimension": "budget",
        "weight": 10,
        "priority": 400,
        "pattern": r"\b(?:бюджет|стоимость|оплата)\b\s*(?:[:=—-]\s*)?(?:до\s*|от\s*)?\d[\d\s]*(?:₽|руб(?:лей|ля|\.)?|р\b|usd|eur|\$|€)",
        "explanation_code": "signal_budget_amount",
    },
    {
        "stable_rule_id": "SIG-CON-001",
        "kind": "signal",
        "target": "contact_present",
        "dimension": "contactability",
        "weight": 3,
        "priority": 440,
        "pattern": r"(?<![\w@])@[a-z0-9_]{5,32}\b",
        "explanation_code": "signal_contact_username",
    },
    {
        "stable_rule_id": "SIG-SPC-002",
        "kind": "signal",
        "target": "task_specificity",
        "dimension": "specificity",
        "weight": 8,
        "priority": 451,
        "pattern": r"\b(?:оплата|авторизация|личный кабинет|админ(?:ка|панель)|каталог|корзина|уведомления|выгрузка|синхронизация)\b",
        "explanation_code": "signal_task_feature",
    },
]
