"""Compatibility facade for bounded public-only graph discovery."""

from telegram_lead_discovery.source_discovery import graph_policy as _policy
from telegram_lead_discovery.source_discovery import graph_repository as _repository
from telegram_lead_discovery.source_discovery import graph_service as _service

ALLOWED_GRAPH_EDGE_TYPES = _policy.ALLOWED_GRAPH_EDGE_TYPES
GRAPH_MESSAGE_SAMPLE_LIMIT = _policy.GRAPH_MESSAGE_SAMPLE_LIMIT
MAX_GRAPH_DEPTH = _policy.MAX_GRAPH_DEPTH
MAX_OUTGOING_EDGES_PER_SEED = _policy.MAX_OUTGOING_EDGES_PER_SEED
MAX_RESOLVE_OPS = _policy.MAX_RESOLVE_OPS
MAX_UNIQUE_GRAPH_CANDIDATES = _policy.MAX_UNIQUE_GRAPH_CANDIDATES
GraphBudget = _policy.GraphBudget
GraphCandidateResult = _policy.GraphCandidateResult
GraphOutcome = _policy.GraphOutcome
GraphQueueItem = _policy.GraphQueueItem
canonical_key_for_snapshot = _policy.canonical_key_for_snapshot
canonical_key_for_username = _policy.canonical_key_for_username
extract_public_usernames_from_text = _policy.extract_public_usernames_from_text
filter_allowed_public_edges = _policy.filter_allowed_public_edges
is_private_invite_ref = _policy.is_private_invite_ref
plan_edge_outcome = _policy.plan_edge_outcome
truncate_outgoing_edges = _policy.truncate_outgoing_edges

ACTIVE_GRAPH_RUN_STATES = _repository.ACTIVE_GRAPH_RUN_STATES
find_active_graph_run = _repository.find_active_graph_run
load_graph_seeds = _repository.load_graph_seeds
_find_existing_source = _repository._find_existing_source
load_registry_index = _repository.load_registry_index

JOB_TYPE_GRAPH_DISCOVERY = _service.JOB_TYPE_GRAPH_DISCOVERY
TERMINAL_GRAPH_RUN_STATES = _service.TERMINAL_GRAPH_RUN_STATES
GraphRunStartError = _service.GraphRunStartError
StartGraphDiscoveryResult = _service.StartGraphDiscoveryResult
_utcnow = _service._utcnow
start_graph_discovery_run = _service.start_graph_discovery_run
collect_edges_for_seed = _service.collect_edges_for_seed
persist_graph_candidate = _service.persist_graph_candidate
