"""Keyword scouting evidence aggregation and opportunity snapshots (SRC-021..025).

Pure domain API for Wave 4 step-09. Does NOT persist rows, call Telegram, or
create TelegramMessage / Lead / outbox / checkpoint (D-052).
"""

from __future__ import annotations

from telegram_lead_discovery.source_discovery.aggregation import (
    AggregationResult,
    ReplacementAcquisitionResult,
    acquire_with_replacement,
    aggregate_search_hits,
    sort_opportunity_snapshots,
)
from telegram_lead_discovery.source_discovery.evidence import (
    EVIDENCE_WINDOW_DAYS,
    HISTORY_SCAN_CAP_PER_RUN,
    HISTORY_SCAN_CAP_PER_SOURCE,
    MAX_EVIDENCE_PER_RUN,
    MAX_MESSAGES_PER_SOURCE,
    MAX_NOISE_EVIDENCE_PER_RUN,
    MAX_QUALIFIED_EVIDENCE_PER_RUN,
    QUALITY_DISTINCT_MIN,
    AnnotatedSearchHit,
    DetectFn,
    DiscoveryChannel,
    EvidenceRecord,
    evidence_from_hit,
    is_within_evidence_window,
    merge_evidence_duplicates,
    qualify_excerpt_text,
)
from telegram_lead_discovery.source_discovery.funnel import (
    POOL_EXHAUSTED_REASON_CODES,
    apply_neutral_noise_sample,
    merge_funnel_counters,
)
from telegram_lead_discovery.source_discovery.identity import (
    PRESENTATION_COOLDOWN,
    DismissedIdentityMatch,
    DismissedKeywordSourceEntry,
    DismissedKeywordSourceIndex,
    PresentationCooldownIndex,
    PresentedIdentityMatch,
    PresentedKeywordSourceEntry,
    PresentedKeywordSourceIndex,
    RegistrySourceEntry,
    ResolvedSourceIdentity,
    SourceRegistryIndex,
    dismissed_telegram_ids,
    is_registry_suppressed,
    presented_telegram_ids,
    registry_telegram_ids,
    resolve_dismissed_identity,
    resolve_presented_identity,
    resolve_source_identity,
)
from telegram_lead_discovery.source_discovery.opportunities import (
    ECOMMERCE_SERVICE_CODE,
    OpportunitySnapshotRecord,
    build_opportunity_from_evidence,
    linked_discussion_opportunity,
)
from telegram_lead_discovery.source_discovery.quality_truth import QUALITY_WINDOW_DAYS
from telegram_lead_discovery.source_discovery.ranking import (
    MAX_DEEP_VERIFICATION_SOURCES,
    PreliminarySourceCandidate,
    build_preliminary_candidates,
    preliminary_rank_key,
    select_sources_for_deep_verification,
)

__all__ = [
    "AggregationResult",
    "AnnotatedSearchHit",
    "DetectFn",
    "DiscoveryChannel",
    "DismissedIdentityMatch",
    "DismissedKeywordSourceEntry",
    "DismissedKeywordSourceIndex",
    "ECOMMERCE_SERVICE_CODE",
    "EVIDENCE_WINDOW_DAYS",
    "EvidenceRecord",
    "HISTORY_SCAN_CAP_PER_RUN",
    "HISTORY_SCAN_CAP_PER_SOURCE",
    "MAX_DEEP_VERIFICATION_SOURCES",
    "MAX_EVIDENCE_PER_RUN",
    "MAX_NOISE_EVIDENCE_PER_RUN",
    "MAX_QUALIFIED_EVIDENCE_PER_RUN",
    "MAX_MESSAGES_PER_SOURCE",
    "QUALITY_DISTINCT_MIN",
    "QUALITY_WINDOW_DAYS",
    "OpportunitySnapshotRecord",
    "POOL_EXHAUSTED_REASON_CODES",
    "PRESENTATION_COOLDOWN",
    "PreliminarySourceCandidate",
    "PresentationCooldownIndex",
    "PresentedIdentityMatch",
    "PresentedKeywordSourceEntry",
    "PresentedKeywordSourceIndex",
    "RegistrySourceEntry",
    "ReplacementAcquisitionResult",
    "ResolvedSourceIdentity",
    "SourceRegistryIndex",
    "acquire_with_replacement",
    "aggregate_search_hits",
    "apply_neutral_noise_sample",
    "build_opportunity_from_evidence",
    "build_preliminary_candidates",
    "evidence_from_hit",
    "dismissed_telegram_ids",
    "is_registry_suppressed",
    "is_within_evidence_window",
    "linked_discussion_opportunity",
    "merge_evidence_duplicates",
    "merge_funnel_counters",
    "preliminary_rank_key",
    "presented_telegram_ids",
    "qualify_excerpt_text",
    "registry_telegram_ids",
    "resolve_dismissed_identity",
    "resolve_presented_identity",
    "resolve_source_identity",
    "select_sources_for_deep_verification",
    "sort_opportunity_snapshots",
]
